#!/bin/bash

docker build -t jakubskopal/mono:4.5 mono
docker tag jakubskopal/mono:4.5 jakubskopal/mono:latest
docker build -t jakubskopal/mono-xsp4:4.5 mono-xsp4
docker tag jakubskopal/mono-xsp4:4.5 jakubskopal/mono:latest


